/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Empleado;

import view.login.menu;
import view.Empleado.menuEmpleado;

/**
 *
 * @author Sebastian Muñoz
 */
public class menuEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form menuCliente
     */
    public menuEmpleado() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        automoviles = new javax.swing.JButton();
        aytarifas = new javax.swing.JButton();
        clientes = new javax.swing.JButton();
        volverallogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        generarreportemenu = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        automoviles.setBackground(new java.awt.Color(0, 204, 255));
        automoviles.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        automoviles.setForeground(new java.awt.Color(255, 255, 255));
        automoviles.setText("Inscribir Automovil");
        automoviles.setBorder(null);
        automoviles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automovilesActionPerformed(evt);
            }
        });
        jPanel1.add(automoviles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 220, 80));

        aytarifas.setBackground(new java.awt.Color(0, 204, 255));
        aytarifas.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        aytarifas.setForeground(new java.awt.Color(255, 255, 255));
        aytarifas.setText("Retirar Automovil");
        aytarifas.setBorder(null);
        aytarifas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aytarifasActionPerformed(evt);
            }
        });
        jPanel1.add(aytarifas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 220, 80));

        clientes.setBackground(new java.awt.Color(0, 204, 255));
        clientes.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        clientes.setForeground(new java.awt.Color(255, 255, 255));
        clientes.setText("Lista de Vehiculos");
        clientes.setBorder(null);
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        jPanel1.add(clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 220, 80));

        volverallogin.setBackground(new java.awt.Color(0, 204, 255));
        volverallogin.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        volverallogin.setForeground(new java.awt.Color(255, 255, 255));
        volverallogin.setText("Volver al Login");
        volverallogin.setBorder(null);
        volverallogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volveralloginActionPerformed(evt);
            }
        });
        jPanel1.add(volverallogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 40));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(207, 207, 207))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 230, 500));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setText("EMPLEADO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        generarreportemenu.setBackground(new java.awt.Color(0, 204, 255));
        generarreportemenu.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        generarreportemenu.setForeground(new java.awt.Color(255, 255, 255));
        generarreportemenu.setText("Generar Reporte");
        generarreportemenu.setBorder(null);
        generarreportemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarreportemenuActionPerformed(evt);
            }
        });
        jPanel1.add(generarreportemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 220, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void automovilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automovilesActionPerformed
    this.setVisible(false);
    inscribirAutomovil a1 = new inscribirAutomovil();
    a1.setVisible(true);
    }//GEN-LAST:event_automovilesActionPerformed

    private void aytarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aytarifasActionPerformed
    this.setVisible(false);
    retirarAutomovil a3 = new retirarAutomovil();
    a3.setVisible(true);
    }//GEN-LAST:event_aytarifasActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
    this.setVisible(false);
    listaVehiculos a5 = new listaVehiculos();
    a5.setVisible(true);
    }//GEN-LAST:event_clientesActionPerformed

    private void volveralloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volveralloginActionPerformed
    this.setVisible(false);
    menu a1 = new menu();
    a1.setVisible(true);
    }//GEN-LAST:event_volveralloginActionPerformed

    private void generarreportemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarreportemenuActionPerformed
    generarReporte a1 = new generarReporte();
    a1.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_generarreportemenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton automoviles;
    private javax.swing.JButton aytarifas;
    private javax.swing.JButton clientes;
    private javax.swing.JButton generarreportemenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton volverallogin;
    // End of variables declaration//GEN-END:variables
}
